application:
  app_name : Neptune
  app_version : v1.1.2
  app_description : Zero Code REST API for RDBMS
  app_prefix : /api/v1
  app_cors_origins : '*'
  app_param_prefix : up_b_
  app_force_generate_meta : #NEPTUNE_application_app_force_generate_meta#
  app_log_level : #NEPTUNE_application_app_log_level#
  app_user_func: #NEPTUNE_application_app_user_func#
  app_exception_detail: #NEPTUNE_application_app_exception_detail#
schema:
  schema_cache_enabled: #NEPTUNE_schema_schema_cache_enabled#
  schema_cache_filename: neptune_metadata
  schema_db_metafile : metadata.json
  schema_fetch_all_table : #NEPTUNE_schema_schema_fetch_all_table#
  schema_fetch_tables : [#NEPTUNE_schema_schema_fetch_tables#]
query:
  query_limit_upset : #NEPTUNE_query_query_limit_upset#
  query_default_limit : #NEPTUNE_query_query_default_limit#
  query_default_offset : #NEPTUNE_query_query_default_offset#
security:
  security_key : 47051d5e3bafcfcba3c80d6d1119a7adf78d2967a8972b00af1ea231ca61f589
  security_algorithm : HS256
  access_token_expire_minutes : #NEPTUNE_security_access_token_expire_minutes#
database:
  db_gendburi : #NEPTUNE_database_db_gendburi#
  db_dialect : #NEPTUNE_database_db_dialect#
  db_drivername : #NEPTUNE_database_db_drivername#
  db_host : #NEPTUNE_database_db_host#
  db_port : #NEPTUNE_database_db_port#
  db_name : #NEPTUNE_database_db_name#
  db_schema : #NEPTUNE_database_db_schema#
  db_use_schema : #NEPTUNE_database_db_use_schema#
  db_username : #NEPTUNE_database_db_username#
  db_password : #NEPTUNE_database_db_password#
  db_uri : #NEPTUNE_database_db_uri#
  db_exclude_tablespaces : [#NEPTUNE_database_db_exclude_tablespaces#]
connection:
  con_pool_size : #NEPTUNE_connection_con_pool_size#
  con_max_overflow : #NEPTUNE_connection_con_max_overflow#
  con_pool_use_lifo : true
  con_pool_pre_ping : true
  con_pool_recycle : #NEPTUNE_connection_con_pool_recycle#