application:
  app_name : Neptune
  app_version : v1.1.2
  app_description : Zero Code REST API for RDBMS
  app_prefix : /api/v1
  app_cors_origins : '*'
  app_param_prefix : up_b_
  app_force_generate_meta : true
  app_log_level : DEBUG
  app_user_func: true
  app_exception_detail: true
schema:
  schema_cache_enabled: true
  schema_cache_filename: neptune_metadata
  schema_db_metafile : metadata.json
  schema_fetch_all_table : true
  schema_fetch_tables : [test,faultmsg]
query:
  query_limit_upset : 2000
  query_default_limit : 20
  query_default_offset : 0
security:
  security_key : 47051d5e3bafcfcba3c80d6d1119a7adf78d2967a8972b00af1ea231ca61f589
  security_algorithm : HS256
  access_token_expire_minutes : 30
database:
  db_gendburi : true
  db_dialect : mysql
  db_drivername : mysql+pymysql
  db_host : 192.168.50.10
  db_port : 3306
  db_name : mysqlsrc
  db_schema : mysqlsrc
  db_use_schema : true
  db_username : root
  db_password : passw0rd
  db_uri : mysql+pymysql://root:passw0rd@192.168.50.10:3306/mysqlsrc
  db_exclude_tablespaces : [SYSTEM,SYSAUX]
connection:
  con_pool_size : 20
  con_max_overflow : 5
  con_pool_use_lifo : true
  con_pool_pre_ping : true
  con_pool_recycle : 3600
